#pragma once
#define INPUTKEY_A 65 
#define INPUTKEY_B 66 
#define INPUTKEY_C 67 
#define INPUTKEY_D 68 
#define INPUTKEY_E 69 
#define INPUTKEY_F 70 
#define INPUTKEY_G 71 
#define INPUTKEY_H 72 
#define INPUTKEY_I 73 
#define INPUTKEY_J 74 
#define INPUTKEY_K 75 
#define INPUTKEY_L 76 
#define INPUTKEY_M 77 
#define INPUTKEY_N 78 
#define INPUTKEY_O 79 
#define INPUTKEY_P 80 
#define INPUTKEY_Q 81 
#define INPUTKEY_R 82 
#define INPUTKEY_S 83 
#define INPUTKEY_T 84 
#define INPUTKEY_U 85 
#define INPUTKEY_V 86 
#define INPUTKEY_W 87 
#define INPUTKEY_X 88 
#define INPUTKEY_Y 89
#define INPUTKEY_Z 90